### PR TITLE
A bit more of a clean up

### PR DESCRIPTION
**Pull request by jamezp**
The first commit cleans up some more of the POM.

The second commit is not required. How do we feel about using the Jakarta Maven coordinates instead of the JBoss ones? I personally like the idea to make it obvious which version of the Jakarta RESTful Web Services we're targeting.

### CODE REVIEW

**Review by asoldano — COMMENTED** [review]
Thanks @jamezp .
Regarding the second commit, it might be fine here, though I fear it might create confusion on why the core resteasy uses the JBoss fork of the spec api (which is because of the tiny additions that has for better JBoss Modules support).

**Comment by liweinan** [comment]
cool!

**Comment by jamezp** [comment]
Okay I went back to the JBoss Spec Version and just upgraded to the Jakarta EE 8 version we package.

**Comment by liweinan** [comment]
@jamezp thanks!

**Comment by jamezp** [comment]
If it looks okay I'll merge it :)

**Pull request merged**
