### PR TITLE
RESTEASY-3054 Replace usages of getParameterTypes().length with getPa…

### PR DESCRIPTION
**Pull request by clara0**
…rameterCount()

https://issues.redhat.com/browse/RESTEASY-3054

### CODE REVIEW

**Review by asoldano — COMMENTED** [review]
Thanks @clara0 , please see https://github.com/resteasy/resteasy/pull/2974#pullrequestreview-818701189

**Comment by rsearls** [comment]
@clara0  since your initial submission module eagledns has been moved from project Resteay
to https://github.com/resteasy/resteasy-extensions.  Please move your changes to this project and submit a PR to that project branch.   It might be helpful to point to this PR in that PR so we know you've been waiting for this.  And you might want to add a comment about this in the jira as well.

**Comment by rsearls** [comment]
@clara0  OOOPs I now see this is for resteasy-extensions.  Sorry for the confusion on my part.

**Review by rsearls — APPROVED** [review]

**Comment by clara0** [comment]
@asoldano Yes, I agree to the ASL 2.0 License terms.

**Pull request merged**
