### PR TITLE
[RESTEASY-2858] Add a utility for encoding parameters and entities for REST end points.

### PR DESCRIPTION
**Pull request by jamezp**
https://issues.redhat.com/browse/RESTEASY-2858

This includes #15. If that PR is merged first I can rebase this.

There are some simple README's to get started. However if this is approved and merged I will look at creating documentation, including the Java Docs, for this project and host that on GitHub.

### CODE REVIEW

**Review by jimma — COMMENTED** [review]
Can we provide EncoderConfiguration with an ContextResolver ?  We can still uses the Provider's priority and don't need to take care of the service loading.

**Comment by jamezp** [comment]
> Can we provide EncoderConfiguration with an ContextResolver ? We can still uses the Provider's priority and don't need to take care of the service loading.

Do you mean removing the `EncoderConfiguration` and using a `ContextResolver` instead? Like we'd just have a `ContextResolver` for specific media types?

**Comment by jimma** [comment]
> > Can we provide EncoderConfiguration with an ContextResolver ? We can still uses the Provider's priority and don't need to take care of the service loading.
> 
> @jimma Do you mean removing the `EncoderConfiguration` and using a `ContextResolver` instead? Like we'd just have a `ContextResolver` for specific media types?

Yes. ContextResolver could be easier for user to write a customized EncoderConfiguraiton.  To  get  this ContextResolver, we can set a MediaType.WILDCARD_TYPE like : 
```
 ContextResolver<EncoderConfiguration> resolver = providerFactory.getContextResolver(EncoderConfiguration.class,MediaType.WILDCARD_TYPE);
```

**Comment by jamezp** [comment]
@jimma Please forgive my ignorance, but I can't find a `ProviderFactory` in the spec. Am I missing something?

**Comment by jamezp** [comment]
@jimma Would doing this just return the context with the highest priority? It sounds like if the `@Produces` is any other type than a wildcard in our case then we'd always get the default. I could be completely wrong though :)

**Comment by jamezp** [comment]
Or I guess actually we could just see if the `ContextResolver` is `null` we provide our own. Sorry, I think that's what you meant and I'm just slow :)

**Comment by TomasHofman** [comment]
@jamezp @jimma just asking - how does this look folks?

**Comment by jamezp** [comment]
@TomasHofman I need to get back to this. I think using the `ParamConverter` like I do here isn't quite right. I've got a bunch of changes locally using a filter instead, but not all the tests pass. I think that is a better approach.

**Comment by TomasHofman** [comment]
@jamezp sounds good, just wanted to have an idea of what's happening. Thanks for information :).

**Pull request closed without merging**
